name: AuthMeColor
version: '1.2.0'
main: rto.plug.authMeColor.AuthMeColor
api-version: '1.20'
authors: [ "Roma_that_ovich" ]
description: "Поддержка HEX и градиентов для AuthMe."
dependencies:
  server:
    AuthMe:
      load: BEFORE
      required: true
    packetevents:
      load: BEFORE
      required: true
